# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6fba3485fcb3877c1eb6de1a5b9f1481057a3a8906b486998f4c04994a347b2765241e02fa7c469b90f077e4f017d1ff1b3c6fcfd5a1f9180a7a763a847d5ad

test:
  secret_key_base: f4067148fba2346bebc7046497d9fa84511a4317ddddd6086577c88ddf37cae779ddf340ac78c46bbf938c641a3139b6b4e9129128ecd5833be7dabd395e7161

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
